name: wordle
version: 1.0.0-alpha.2
publish_to: none
description: A new Flutter project for Wordle game.
environment: 
  sdk: '>=2.16.2 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.1
  english_words: ^4.0.0
  jiffy: ^5.0.0
  package_info_plus: ^1.4.2
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^1.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

