name: wordle
version: 1.0.0-alpha.2
publish_to: none
description: A new Flutter project for Wordle game.
environment: 
  sdk: '>=2.16.2 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.1
  jiffy: ^5.0.0
  flutter:
    sdk: flutter
  all_english_words: ^1.0.3

dev_dependencies: 
  flutter_lints: ^1.0.0
  flutter_test: 
    sdk: flutter

flutter:
  uses-material-design: true

